### ISSUE TITLE
Navigation hover states

### ISSUE THREAD

**Issue by caitlynmayers** [tfuqua/ukrops#11]
### Location

Globally
### Description

I added two tags to Zeplin to help you ID what needs to be adjusted, but the primary navigation hover states are not per the comp (easy to miss, so no worries.)
### Screenshot

<img width="224" alt="screen shot 2016-10-25 at 9 50 26 am" src="https://cloud.githubusercontent.com/assets/1574420/19688615/7aa7e2da-9a98-11e6-9941-b0c99d1fb0c6.png">

**Comment by tfuqua** [comment]
I removed the underline text decoration when hovering over menu item
