### ISSUE TITLE
Navigation type sizes, weights

### ISSUE THREAD

**Issue by caitlynmayers** [tfuqua/ukrops#12]
### Location

Globally
### Description

The primary navigation type size is not large enough - should be 20px at desktop - and this is causing the utility navigation to feel too large. Please bump up the primary navigation size and make sure the padding around the links is equal. The utility navigation font weight is currently too heavy, please reduce to match comp.
#### Current Results

<img width="1296" alt="screen shot 2016-10-25 at 9 52 24 am" src="https://cloud.githubusercontent.com/assets/1574420/19688712/c4463158-9a98-11e6-97e8-dd9199adc15c.png">
#### Expected Results

<img width="1002" alt="screen shot 2016-10-25 at 9 53 13 am" src="https://cloud.githubusercontent.com/assets/1574420/19688735/e242d62a-9a98-11e6-933a-662f258c63ef.png">

**Comment by tfuqua** [comment]
@caitlynmayers We can easily update this font size. I originally had asked @agentdoublel if it would be ok for me to reduce the font size to help prevent the menu from going onto multiple lines on smaller screen widths, right before we snap to mobile menu.

**Comment by caitlynmayers** [comment]
@tfuqua that's ok, but please make the font size smaller only when you need to on the smaller screens.

**Comment by tfuqua** [comment]
Sounds good!

**Comment by tfuqua** [comment]
Font sizes were updated for menus to render correctly and on one line on desktop devices

**Comment by agentdoublel** [comment]
I think the top nav text size looks too large now in comparison to the secondary one.

**Comment by tfuqua** [comment]
Reduced top nav 1px to not look as large in relation to main nav

**Comment by tfuqua** [comment]
Closing this issue as font sizes have been updated
