### ISSUE TITLE
Blog List - Hero Area

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#13]
### Location
Blog List view, Hero area

### Description
- Round corners of white box 
- More padding around the text (See comp)
- Can you confirm the body text is 18px ?

### Screenshot
![screen shot 2016-11-08 at 10 29 02 am](https://cloud.githubusercontent.com/assets/17103891/20105299/1870496a-a59f-11e6-8aab-6d916305b156.png)

**Comment by tfuqua** [comment]
Updated Padding and rounded corners. Font size is 18px
