### ISSUE TITLE
Blog list - Add Category border

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#14]
### Location
Blog list view - Category list

### Description
There should be a dotted border with a drop shadow seperating the cards and the categories
(See comp)

### Screenshot
![screen shot 2016-11-08 at 10 37 01 am](https://cloud.githubusercontent.com/assets/17103891/20105346/4dcf205e-a59f-11e6-8e09-b33c271733da.png)

**Comment by agentdoublel** [comment]
Needs to be full length of page

**Comment by tfuqua** [comment]
Similar to issue #24, updated border to take up 100% height of the page.

**Comment by caitlynmayers** [comment]
Fix verified.
