### ISSUE TITLE
Blog list - Card styling

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#15]
### Location
Blog list view, Cards

### Description
- Title text is too large, let's scale it down to 26px
- Body text looks to large, let's scale that down to 16px
- Title should also be all caps
- Padding between the outside of the text and the inside of the white box is too small (see comp)

### Screenshot
![screen shot 2016-11-08 at 10 41 15 am](https://cloud.githubusercontent.com/assets/17103891/20105530/e68c4592-a59f-11e6-8d40-df96b6c5f79c.png)

**Comment by tfuqua** [comment]
Updated font sizes, and updated card padding to 22px per comp

**Comment by agentdoublel** [comment]
Perfection!
