### ISSUE TITLE
Story - Hero title

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#16]
### Location
Ukrop's Story , Hero area

### Description
Can we reduce the number of columns that the quote takes up? EX: if it's 8 columns now can we do 6?

### Screenshot
![screen shot 2016-11-09 at 1 45 52 pm](https://cloud.githubusercontent.com/assets/17103891/20150250/dd47c1ee-a682-11e6-9fe7-dda237af454a.png)

**Comment by tfuqua** [comment]
Updated the max width to 8 columns (720px)
