### ISSUE TITLE
Story - Gradient tweak

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#18]
### Location
Ukrops story, Meet the food team section

### Description
The gradient needs to start above "meet the food team"

### Screenshot
![screen shot 2016-11-09 at 2 15 28 pm](https://cloud.githubusercontent.com/assets/17103891/20151125/ff67a0a6-a686-11e6-9033-f08ebb6ef47b.png)

**Comment by tfuqua** [comment]
Closing issue as marked 'low-priority'
