### ISSUE TITLE
Community - Partners logo sizes

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#19]
### Location
Community, Community Partners

### Description
Logos seem to large. Can we make them a max height of 170px or width of 300px? Whichever works out

### Screenshot
![screen shot 2016-11-09 at 2 18 20 pm](https://cloud.githubusercontent.com/assets/17103891/20151248/6dd9ae26-a687-11e6-8a46-13335334acc2.png)

**Comment by tfuqua** [comment]
I set images to 75% width of their container (easy for responsive design). I also vertically aligned content to the center of the page and that seems to help

**Comment by agentdoublel** [comment]
This doesnt look any different :o

**Comment by agentdoublel** [comment]
Oh wait, they're aligned, but they're still super big

**Comment by tfuqua** [comment]
Reduced width from 75% to 60% of its container

**Comment by caitlynmayers** [comment]
Fix verified.
