### ISSUE TITLE
Headline change

### ISSUE THREAD

**Issue by kevinjflores** [tfuqua/ukrops#2]
### Location

H1 Headline
### Description

H1 - Change "everything" to "what" in the headline. Just trying to get rid of the ("do") widow on multiple breakpoints.
### Screenshot

![image](https://cloud.githubusercontent.com/assets/22937737/19525947/b08c4708-95f0-11e6-9dc2-cd6be87dfcca.png)

**Comment by caitlynmayers** [comment]
Fix verified.
