### ISSUE TITLE
Community - Full width image issue

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#20]
### Location
Community, content area

### Description
Full width image should crop instead of scale down

### Screenshot
![screen shot 2016-11-09 at 2 23 11 pm](https://cloud.githubusercontent.com/assets/17103891/20151415/10dd74ae-a688-11e6-8873-a8bae6a70b6a.png)

**Comment by tfuqua** [comment]
Jeff removed that content. closing as no longer an issue
