### ISSUE TITLE
Story - Logo family stretching 

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#21]
### Location
Ukrops story, The Ukrops Family

### Description
Logos are getting stretched at a certain view

### Screenshot
![screen shot 2016-11-09 at 2 25 17 pm](https://cloud.githubusercontent.com/assets/17103891/20151596/b1010716-a688-11e6-94b7-6efaa4388840.png)

**Comment by tfuqua** [comment]
My CSS was dumb. this should be resolved

**Comment by agentdoublel** [comment]
LOL. <3
