### ISSUE TITLE
Search - Result title size

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#22]
### Location
Search result page

### Description
The result heading looks too large (which is my bad) let's change it from an h2 to and h4

### Screenshot
<img width="1026" alt="screen shot 2016-11-10 at 10 14 50 am" src="https://cloud.githubusercontent.com/assets/17103891/20182074/8b91e508-a72e-11e6-991c-525369eab6cb.png">

**Comment by agentdoublel** [comment]
@tfuqua can we also show 2 full lines of copy?

**Comment by tfuqua** [comment]
Created custom excerpt method. Updated to 40 words for search results
