### ISSUE TITLE
Food Team - Padding in mobile

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#23]
### Location
Food team mobile view

### Description
Let's add some padding under the photos in mobile

### Screenshot
<img width="382" alt="screen shot 2016-11-10 at 10 21 06 am" src="https://cloud.githubusercontent.com/assets/17103891/20182361/840a19e4-a72f-11e6-81d9-59f89989702b.png">

**Comment by tfuqua** [comment]
Added 20px of padding below images on mobile
