### ISSUE TITLE
Food team - Needs divider

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#24]
### Location
Food team

### Description
We need to add that dividing dashed line with shadow

### Screenshot
<img width="477" alt="screen shot 2016-11-10 at 10 24 34 am" src="https://cloud.githubusercontent.com/assets/17103891/20182482/e7e1ea78-a72f-11e6-9f12-ce9d7b4f419b.png">

**Comment by agentdoublel** [comment]
It's almost there! Needs to be the height of the page.

**Comment by tfuqua** [comment]
Updated CSS to take up 100% height

**Comment by caitlynmayers** [comment]
Fix verified.
