### ISSUE TITLE
Global - category divider

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#28]
### Location
Globally (any page with the side category)

### Description
The divider is not to spec. Should be full length and match the width on the comp

### Screenshot
<img width="76" alt="screen shot 2016-11-16 at 11 27 48 am" src="https://cloud.githubusercontent.com/assets/17103891/20355592/d7b00170-abef-11e6-854c-c39c6d43eb60.png">

**Comment by tfuqua** [comment]
This is similar to issue #24. Updated the border to take up the entire height of the page

**Comment by caitlynmayers** [comment]
Fix verified.
