### ISSUE TITLE
Remove border on store locator page

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#33]
### Location
Store locator

### Description
Take off the border for the side. This is totally my fault because I logged it as a bug and I'm so sorry. D: I tried to fix it before you got to it.

### Screenshot
<img width="185" alt="screen shot 2016-11-30 at 10 19 36 am" src="https://cloud.githubusercontent.com/assets/17103891/20759546/327b949c-b6eb-11e6-9d6f-4de6ea08e7cb.png">

**Comment by tfuqua** [comment]
removed border back to how it was originally
