### ISSUE TITLE
Store locator search not showing in mobile

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#37]
### Location
MOBILE - Store Locator

### Description
Are we not showing the store locator fields or results on mobile?

### Screenshot

**Comment by tfuqua** [comment]
This issue should be resolved now that I fixed the border markup. Oversight on my part

**Comment by agentdoublel** [comment]
@tfuqua Awesome! On the mobile Store Locator landing page, can you add like 10px of padding under the "Search" button?

**Comment by tfuqua** [comment]
updated to 15px margin below button
