### ISSUE TITLE
Mobile : Strange blog issue

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#38]
### Location
Blog card view

### Description
On the card view of blog there's a strange strip of white that shows up on the left side of the screen and if you refresh it does away, but then the cards aren't center aligned. 

### Screenshot
![img_1584](https://cloud.githubusercontent.com/assets/17103891/20769790/4f9e377a-b711-11e6-87ff-d169865f32f2.PNG)

**Comment by tfuqua** [comment]
The white section I think you meant was on the right side of the screen? That is now resolved.

**Comment by agentdoublel** [comment]
@tfuqua I'm an idiot. You're right. -_-
