### ISSUE TITLE
Mobile: Global Navigation tablet/horizontal mobile

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#39]
### Location
Global nav

### Description
The global nav covers the page specific nav in horizontal mobile/small tablet. Can we just have it be AFTER the primary?

### Screenshot
![img_1588](https://cloud.githubusercontent.com/assets/17103891/20771455/73fce91c-b717-11e6-9fc8-1e6730b15294.PNG)

**Comment by tfuqua** [comment]
So the technical issue here is that on full width devices we have the extra nav menu above the main menu, but on smaller devices we have the extra nav appearing below the main navigation, so I am forced to use fixed positioning to keep it at the bottom of the page. Is the user able to scroll the past the bottom menu at all?

**Comment by agentdoublel** [comment]
@tfuqua No, I'm not able to scroll past the bottom menu.
