### ISSUE TITLE
Header logo placement on mobile

### ISSUE THREAD

**Issue by kevinjflores** [tfuqua/ukrops#4]
### Location

Header
### Description

In mobile view: Change placement of header logo to left-justified
### Screenshot

![image](https://cloud.githubusercontent.com/assets/22937737/19526154/7b7ccc44-95f1-11e6-9408-199106cdbf64.png)

**Comment by caitlynmayers** [comment]
@tfuqua can you add padding-left: 10px; to that logo?

**Comment by tfuqua** [comment]
Yep Yep, will update and commit

**Comment by caitlynmayers** [comment]
Fix verified.
