### ISSUE TITLE
Global: Hero content issue

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#41]
### Location
Globally, Hero area

### Description
The fields show up in the CMS to customize the hero/header content, but stuff shows even if you havent submitted anything

### Screenshot
<img width="719" alt="screen shot 2016-12-01 at 4 20 50 pm" src="https://cloud.githubusercontent.com/assets/17103891/20813058/2b4aac38-b7e2-11e6-8ad8-84439223b712.png">

**Comment by tfuqua** [comment]
resolved
