### ISSUE TITLE
right padding of community partners logos

### ISSUE THREAD

**Issue by caitlynmayers** [tfuqua/ukrops#43]
### Location
http://ukrops.taylorfuqua.com/the-ukrops-story/community/

### Description
The logos all have right padding, which makes the logos appear misaligned. Use nth child to remove this from the third image or add even padding to both the left and right of the image to achieve the separation and keep it even.

### Screenshot
<img width="1150" alt="screen shot 2016-12-14 at 11 39 44 am" src="https://cloud.githubusercontent.com/assets/1574420/21191090/0d0ab668-c1f2-11e6-973c-41d5b46e9f23.png">

**Comment by tfuqua** [comment]
This has been fixed and deployed
