### ISSUE TITLE
Footer illustration

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops#9]
### Location

Footer
### Description

Illustration in footer scales down, but should just crop like in the comp. Also needs textured background. 
### Screenshot

<img width="404" alt="screen shot 2016-10-20 at 11 51 56 am" src="https://cloud.githubusercontent.com/assets/17103891/19567591/455c9830-96bc-11e6-950b-3778b7f1d7b2.png">

**Comment by caitlynmayers** [comment]
Fix verified.
